name: CI linting and testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install apt packages
      run: |
        sudo apt install -y libgnutls28-dev openssl ninja-build pkg-config libboost-dev cmake libgtest-dev
    - name: Install apt needed to build libcamera
      run: |
        sudo pip3 install meson jinja2 ply yaml
    - name: Install libcamera
      run: |
        bash deploy/install_libcamera.sh
    - name: Install python packages for the build of the wrapper
      run: |
        pip3 install -r requirements.txt
    - name: Build the package
      run: |
        python3 setup.py build
